const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, 'backend/controllers/auth.controller.ts');
let content = fs.readFileSync(file, 'utf8');

const updatedType = `type UserWithRelations = InferSelectModel<typeof authentication> & {
  hrDetails?: {
    id: number;
    department?: { id: number; name: string } | null;
    position?: { positionTitle: string | null } | null;
    jobTitle: string | null;
    employmentStatus: string | null;
    appointmentType: string | null;
    dateHired: string | null;
    dutyType: string | null;
    profileStatus: string | null;
    isMeycauayan?: boolean | null;
  } | null;
  pdsEducations?: { schoolName: string | null }[] | null;
  duties?: string | null;
  shift?: string | null;
  // added missing properties
  address?: string | null;
  residentialAddress?: string | null;
  permanentAddress?: string | null;
  emergencyContact?: string | null;
  emergencyContactNumber?: string | null;
  educationalBackground?: string | null;
  mobileNo?: string | null;
  telephoneNo?: string | null;
  agencyEmployeeNo?: string | null;
  dualCountry?: string | null;
  govtIdType?: string | null;
  govtIdNo?: string | null;
  govtIdIssuance?: string | null;
  birthDate?: string | null;
  placeOfBirth?: string | null;
  gender?: string | null;
  civilStatus?: string | null;
  nationality?: string | null;
  residentialZipCode?: string | null;
  permanentZipCode?: string | null;
  resHouseBlockLot?: string | null;
  resStreet?: string | null;
  resSubdivision?: string | null;
  resCity?: string | null;
  resProvince?: string | null;
  permHouseBlockLot?: string | null;
  permStreet?: string | null;
  permSubdivision?: string | null;
  permCity?: string | null;
  permProvince?: string | null;
  umidNumber?: string | null;
  philsysId?: string | null;
  gsisNumber?: string | null;
  philhealthNumber?: string | null;
  pagibigNumber?: string | null;
  tinNumber?: string | null;
  schoolName?: string | null;
  course?: string | null;
  yearGraduated?: string | null;
  eligibilityType?: string | null;
  eligibilityNumber?: string | null;
  eligibilityDate?: string | null;
  yearsOfExperience?: string | null;
  bloodType?: string | null;
  heightM?: string | null;
  weightKg?: string | null;
  relatedThirdDegree?: string | null;
  relatedThirdDetails?: string | null;
  relatedFourthDegree?: string | null;
  relatedFourthDetails?: string | null;
  foundGuiltyAdmin?: string | null;
  foundGuiltyDetails?: string | null;
  criminallyCharged?: string | null;
  dateFiled?: string | null;
  statusOfCase?: string | null;
  convictedCrime?: string | null;
  convictedDetails?: string | null;
  separatedFromService?: string | null;
  separatedDetails?: string | null;
  electionCandidate?: string | null;
  electionDetails?: string | null;
  resignedToPromote?: string | null;
  resignedDetails?: string | null;
  immigrantStatus?: string | null;
  immigrantDetails?: string | null;
  indigenousMember?: string | null;
  indigenousDetails?: string | null;
  personWithDisability?: string | null;
  disabilityIdNo?: string | null;
  soloParent?: string | null;
  soloParentIdNo?: string | null;
  dateAccomplished?: string | null;
  pdsQuestions?: string | null;
};`;

content = content.replace(/type UserWithRelations = InferSelectModel<typeof authentication> & \{[\s\S]*?\n\};/, updatedType);
fs.writeFileSync(file, content);
console.log('auth.controller.ts updated');
