
import { db } from '../db/index.js';
import { 
    attendanceLogs, 
    authentication 
} from '../db/schema.js';
import { eq } from 'drizzle-orm';
import moment from 'moment';
import { processDailyAttendance } from '../services/attendanceProcessor.js';

async function simulateAttendance() {
    console.log('🚀 Starting TRUE Attendance Simulation (Jan 5 - Feb 17, 2026)...');
    console.log('   Mode: Insert Logs -> Trigger Processor (Real-world Flow)');

    // 1. Get CHRMO Employees
    const employees = await db.query.authentication.findMany({
        where: eq(authentication.department, 'CHRMO'),
    });

    if (employees.length === 0) {
        console.error('❌ No CHRMO employees found. Please run seed_chrmo.ts first.');
        process.exit(1);
    }

    const startDate = moment('2026-01-05');
    const endDate = moment('2026-02-17');

    let currentDate = startDate.clone();
    let totalLogs = 0;
    
    // We will process day by day
    while (currentDate.isSameOrBefore(endDate)) {
        // Skip Weekends
        if (currentDate.day() === 0 || currentDate.day() === 6) {
            currentDate.add(1, 'days');
            continue;
        }

        const dateStr = currentDate.format('YYYY-MM-DD');
        console.log(`📅 Processing ${dateStr}...`);

        for (const emp of employees) {
            // Randomize Attendance Behavior
            const rand = Math.random();
            let timeIn = '08:00:00';
            let timeOut = '17:00:00';
            let isAbsent = false;

            // Scenario Distribution:
            // 80% Present (On Time/Early)
            // 10% Late
            // 5% Undertime
            // 5% Absent

            if (rand < 0.80) {
                // On Time: 7:30 - 8:00
                const mins = Math.floor(Math.random() * 30);
                timeIn = `07:${30 + mins}:00`;
                const outMins = Math.floor(Math.random() * 30);
                timeOut = `17:${outMins.toString().padStart(2, '0')}:00`;
            } else if (rand < 0.90) {
                // Late: 8:01 - 8:45
                const mins = Math.floor(Math.random() * 44) + 1;
                timeIn = `08:${mins.toString().padStart(2, '0')}:00`;
            } else if (rand < 0.95) {
                // Undertime: Out at 4:00 - 4:59
                timeIn = '07:55:00';
                timeOut = `16:${Math.floor(Math.random() * 59).toString().padStart(2, '0')}:00`;
            } else {
                isAbsent = true;
            }

            if (!isAbsent) {
                // Create Timestamps
                // We need full MySQL Datetime: YYYY-MM-DD HH:mm:ss
                const scanTimeIn = `${dateStr} ${timeIn}`;
                const scanTimeOut = `${dateStr} ${timeOut}`;

                // Insert IN Log
                await db.insert(attendanceLogs).values({
                    employeeId: emp.employeeId,
                    scanTime: scanTimeIn,
                    type: 'IN',
                    source: 'SIMULATION'
                } as any);

                // Insert OUT Log
                await db.insert(attendanceLogs).values({
                    employeeId: emp.employeeId,
                    scanTime: scanTimeOut,
                    type: 'OUT',
                    source: 'SIMULATION'
                } as any);

                totalLogs += 2;

                // CRITICAL STEP: Trigger the Processor
                // This will calculate late/undertime and insert/update the DTR table
                try {
                    await processDailyAttendance(emp.employeeId, dateStr);
                } catch (error) {
                    console.error(`Error processing ${emp.employeeId} on ${dateStr}:`, error);
                }
            } else {
                // If absent, we usually don't have logs. 
                // The DTR will be missing or marked absent by a cron job in real life.
                // For simulation visualization, we can optionally explicitly mark absent or leave it blank.
                // Let's leave it blank to simulate "No Show".
                // OR: Call processor with no logs? No, processor relies on logs.
                // Real system handles absences via nightly cron.
            }
        }
        currentDate.add(1, 'days');
    }

    console.log(`✅ Simulation Complete.`);
    console.log(`- Logs Created: ${totalLogs}`); 
    console.log(`- DTR Records: Automatically generated by processor.`);
    process.exit(0);
}

simulateAttendance().catch(err => {
    console.error(err);
    process.exit(1);
});
