import { mysqlTable, varchar, int, date, timestamp, decimal, text, mysqlEnum, datetime, unique, boolean, foreignKey, primaryKey, json } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';
import { departments } from './hr.js';
import { plantillaPositions } from './plantilla.js';

export const authentication = mysqlTable("authentication", {
	id: int("id").autoincrement().notNull(),
	firstName: varchar("first_name", { length: 100 }).notNull(),
	lastName: varchar("last_name", { length: 100 }).notNull(),
	middleName: varchar("middle_name", { length: 100 }),
	suffix: varchar("suffix", { length: 20 }),
	email: varchar("email", { length: 255 }).notNull(),
	role: varchar("role", { length: 50 }).notNull(),
	department: varchar("department", { length: 100 }), 
	departmentId: int("department_id").references(() => departments.id, { onDelete: "set null" } ),
	employeeId: varchar("employee_id", { length: 50 }),
	rfidCardUid: varchar("rfid_card_uid", { length: 50 }),
	passwordHash: varchar("password_hash", { length: 255 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	isVerified: boolean("is_verified").default(false),
	verificationToken: varchar("verification_token", { length: 255 }),
	resetPasswordToken: varchar("reset_password_token", { length: 255 }),
	resetPasswordExpires: datetime("reset_password_expires", { mode: 'string'}),
	googleId: varchar("google_id", { length: 255 }),
	avatarUrl: varchar("avatar_url", { length: 500 }),
	jobTitle: varchar("job_title", { length: 100 }),
	employmentStatus: mysqlEnum("employment_status", ['Active','Probationary','Terminated','Resigned','On Leave','Suspended','Verbal Warning','Written Warning','Show Cause']).default('Active'),
	employmentType: varchar("employment_type", { length: 50 }).default('Probationary'),
	dateHired: date("date_hired", { mode: 'string' }),
	contractEndDate: date("contract_end_date", { mode: 'string' }),
	regularizationDate: date("regularization_date", { mode: 'string' }),
	isRegular: boolean("is_regular").default(false),
	managerId: int("manager_id"),
	birthDate: date("birth_date", { mode: 'string' }),
	gender: mysqlEnum("gender", ['Male','Female']),
	civilStatus: mysqlEnum("civil_status", ['Single','Married','Widowed','Separated','Annulled']),
	nationality: varchar("nationality", { length: 50 }).default('Filipino'),
	bloodType: varchar("blood_type", { length: 5 }),
	heightCm: decimal("height_cm", { precision: 5, scale: 2 }),
	heightM: decimal("height_m", { precision: 4, scale: 2 }),
	weightKg: decimal("weight_kg", { precision: 5, scale: 2 }),
	phoneNumber: varchar("phone_number", { length: 20 }),
	address: text("address"),
	permanentAddress: text("permanent_address"),
	emergencyContact: varchar("emergency_contact", { length: 100 }),
	emergencyContactNumber: varchar("emergency_contact_number", { length: 20 }),
	umidNumber: varchar("umid_no", { length: 50 }),
	philsysId: varchar("philsys_id", { length: 50 }),
	philhealthNumber: varchar("philhealth_number", { length: 50 }),
	pagibigNumber: varchar("pagibig_number", { length: 50 }),
	tinNumber: varchar("tin_number", { length: 50 }),
	gsisNumber: varchar("gsis_number", { length: 50 }),
	agencyEmployeeNo: varchar("agency_employee_no", { length: 50 }),
	salaryGrade: varchar("salary_grade", { length: 10 }),
	stepIncrement: int("step_increment").default(1),
	appointmentType: mysqlEnum("appointment_type", ['Permanent','Contractual','Casual','Job Order','Coterminous','Temporary','Contract of Service','JO','COS']),
	officeAddress: text("office_address"),
	station: varchar("station", { length: 100 }),
	positionTitle: varchar("position_title", { length: 100 }),
	itemNumber: varchar("item_number", { length: 50 }),
	positionId: int("position_id").references(() => plantillaPositions.id, { onDelete: "set null" } ),

	firstDayOfService: date("first_day_of_service", { mode: 'string' }),
	refreshToken: text("refresh_token"),
	twoFactorEnabled: boolean("two_factor_enabled").default(false),
	twoFactorOtp: varchar("two_factor_otp", { length: 6 }),
	twoFactorOtpExpires: datetime("two_factor_otp_expires", { mode: 'string'}),
	eligibilityType: varchar("eligibility_type", { length: 255 }),
	eligibilityNumber: varchar("eligibility_number", { length: 100 }),
	eligibilityDate: date("eligibility_date", { mode: 'string' }),
	educationalBackground: text("educational_background"),
	schoolName: varchar("school_name", { length: 255 }),
	course: varchar("course", { length: 255 }),
	yearGraduated: varchar("year_graduated", { length: 10 }),
	yearsOfExperience: varchar("years_of_experience", { length: 50 }),
	experience: text("experience"),
	skills: text("skills"),
	placeOfBirth: varchar("place_of_birth", { length: 255 }),
	residentialAddress: text("residential_address"),
	residentialZipCode: varchar("residential_zip_code", { length: 50 }),
	permanentZipCode: varchar("permanent_zip_code", { length: 50 }),
	telephoneNo: varchar("telephone_no", { length: 50 }),
	mobileNo: varchar("mobile_no", { length: 50 }),
	originalAppointmentDate: date("original_appointment_date", { mode: 'string' }),
	lastPromotionDate: date("last_promotion_date", { mode: 'string' }),
	facebookUrl: varchar("facebook_url", { length: 255 }),
	linkedinUrl: varchar("linkedin_url", { length: 255 }),
	twitterHandle: varchar("twitter_handle", { length: 100 }),
	religion: varchar("religion", { length: 100 }),
	citizenship: varchar("citizenship", { length: 50 }).default('Filipino'),
	citizenshipType: varchar("citizenship_type", { length: 50 }),
	barangay: varchar("barangay", { length: 100 }),
	dutyType: mysqlEnum("duty_type", ['Standard', 'Irregular']).default('Standard'),
	dailyTargetHours: decimal("daily_target_hours", { precision: 4, scale: 2 }).default('8.00'),
	salaryBasis: mysqlEnum("salary_basis", ['Daily','Hourly']).default('Daily'),
	resHouseBlockLot: varchar("res_house_block_lot", { length: 150 }),
	resStreet: varchar("res_street", { length: 150 }),
	resSubdivision: varchar("res_subdivision", { length: 150 }),
	resBarangay: varchar("res_barangay", { length: 150 }),
	resCity: varchar("res_city", { length: 150 }),
	resProvince: varchar("res_province", { length: 150 }),
	resRegion: varchar("res_region", { length: 150 }),
	permHouseBlockLot: varchar("perm_house_block_lot", { length: 150 }),
	permStreet: varchar("perm_street", { length: 150 }),
	permSubdivision: varchar("perm_subdivision", { length: 150 }),
	permBarangay: varchar("perm_barangay", { length: 150 }),
	permCity: varchar("perm_city", { length: 150 }),
	permProvince: varchar("perm_province", { length: 150 }),
	permRegion: varchar("perm_region", { length: 150 }),
	profileStatus: mysqlEnum("profile_status", ['Initial', 'Complete']).default('Initial'),
	rightThumbmarkUrl: varchar("right_thumbmark_url", { length: 500 }),
	ctcNo: varchar("ctc_no", { length: 50 }),
	ctcIssuedAt: varchar("ctc_issued_at", { length: 255 }),
	ctcIssuedDate: date("ctc_issued_date", { mode: 'string' }),
	loginAttempts: int("login_attempts").default(0),
	lockUntil: datetime("lock_until", { mode: 'string'}),
	startTime: varchar("start_time", { length: 50 }),
	endTime: varchar("end_time", { length: 50 }),
	isOldEmployee: boolean("is_old_employee").default(false),
	motherMaidenName: varchar("mother_maiden_name", { length: 255 }),
	spouseName: varchar("spouse_name", { length: 255 }),
	fatherName: varchar("father_name", { length: 255 }),
},
(table) => [
	foreignKey({
			columns: [table.managerId],
			foreignColumns: [table.id],
			name: "fk_manager"
		}).onDelete("set null"),
	primaryKey({ columns: [table.id], name: "authentication_id"}),
	unique("email").on(table.email),
	unique("employee_id").on(table.employeeId),
	unique("google_id").on(table.googleId),
	unique("umid_no_unique").on(table.umidNumber),
	unique("philsys_id_unique").on(table.philsysId),
	unique("philhealth_no_unique").on(table.philhealthNumber),
	unique("pagibig_no_unique").on(table.pagibigNumber),
	unique("tin_no_unique").on(table.tinNumber),
	unique("gsis_no_unique").on(table.gsisNumber),
]);

export const googleCalendarTokens = mysqlTable("google_calendar_tokens", {
	userId: int("user_id").notNull().references(() => authentication.id, { onDelete: "cascade" } ),
	accessToken: text("access_token").notNull(),
	refreshToken: text("refresh_token").notNull(),
	tokenExpiry: datetime("token_expiry", { mode: 'string'}).notNull(),
	syncEnabled: boolean("sync_enabled").default(true),
	calendarId: varchar("calendar_id", { length: 255 }).default('primary'),
	lastSync: datetime("last_sync", { mode: 'string'}).default(sql`(CURRENT_TIMESTAMP)`),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.userId], name: "google_calendar_tokens_user_id"}),
]);

export const socialConnections = mysqlTable("social_connections", {
	id: int("id").autoincrement().notNull(),
	userId: int("user_id").notNull().references(() => authentication.id, { onDelete: "cascade" } ),
	provider: mysqlEnum("provider", ['facebook','jobstreet']).notNull(),
	providerUserId: varchar("provider_user_id", { length: 100 }).notNull(),
	providerUserName: varchar("provider_user_name", { length: 255 }),
	accessToken: text("access_token"),
	refreshToken: text("refresh_token"),
	expiresAt: datetime("expires_at", { mode: 'string'}),
	metadata: json("metadata"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "social_connections_id"}),
	unique("unique_user_provider").on(table.userId, table.provider),
]);


