"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.socialConnections = exports.googleCalendarTokens = exports.authentication = void 0;
var mysql_core_1 = require("drizzle-orm/mysql-core");
var drizzle_orm_1 = require("drizzle-orm");
var hr_js_1 = require("./hr.js");
var plantilla_js_1 = require("./plantilla.js");
exports.authentication = (0, mysql_core_1.mysqlTable)("authentication", {
    id: (0, mysql_core_1.int)("id").autoincrement().notNull(),
    firstName: (0, mysql_core_1.varchar)("first_name", { length: 100 }).notNull(),
    lastName: (0, mysql_core_1.varchar)("last_name", { length: 100 }).notNull(),
    middleName: (0, mysql_core_1.varchar)("middle_name", { length: 100 }),
    suffix: (0, mysql_core_1.varchar)("suffix", { length: 20 }),
    email: (0, mysql_core_1.varchar)("email", { length: 255 }).notNull(),
    role: (0, mysql_core_1.varchar)("role", { length: 50 }).notNull(),
    department: (0, mysql_core_1.varchar)("department", { length: 100 }),
    departmentId: (0, mysql_core_1.int)("department_id").references(function () { return hr_js_1.departments.id; }, { onDelete: "set null" }),
    employeeId: (0, mysql_core_1.varchar)("employee_id", { length: 50 }),
    rfidCardUid: (0, mysql_core_1.varchar)("rfid_card_uid", { length: 50 }),
    passwordHash: (0, mysql_core_1.varchar)("password_hash", { length: 255 }),
    createdAt: (0, mysql_core_1.timestamp)("created_at", { mode: 'string' }).defaultNow(),
    isVerified: (0, mysql_core_1.boolean)("is_verified").default(false),
    verificationToken: (0, mysql_core_1.varchar)("verification_token", { length: 255 }),
    resetPasswordToken: (0, mysql_core_1.varchar)("reset_password_token", { length: 255 }),
    resetPasswordExpires: (0, mysql_core_1.datetime)("reset_password_expires", { mode: 'string' }),
    googleId: (0, mysql_core_1.varchar)("google_id", { length: 255 }),
    avatarUrl: (0, mysql_core_1.varchar)("avatar_url", { length: 500 }),
    jobTitle: (0, mysql_core_1.varchar)("job_title", { length: 100 }),
    employmentStatus: (0, mysql_core_1.mysqlEnum)("employment_status", ['Active', 'Probationary', 'Terminated', 'Resigned', 'On Leave', 'Suspended', 'Verbal Warning', 'Written Warning', 'Show Cause']).default('Active'),
    employmentType: (0, mysql_core_1.varchar)("employment_type", { length: 50 }).default('Probationary'),
    dateHired: (0, mysql_core_1.date)("date_hired", { mode: 'string' }),
    contractEndDate: (0, mysql_core_1.date)("contract_end_date", { mode: 'string' }),
    regularizationDate: (0, mysql_core_1.date)("regularization_date", { mode: 'string' }),
    isRegular: (0, mysql_core_1.boolean)("is_regular").default(false),
    managerId: (0, mysql_core_1.int)("manager_id"),
    birthDate: (0, mysql_core_1.date)("birth_date", { mode: 'string' }),
    gender: (0, mysql_core_1.mysqlEnum)("gender", ['Male', 'Female']),
    civilStatus: (0, mysql_core_1.mysqlEnum)("civil_status", ['Single', 'Married', 'Widowed', 'Separated', 'Annulled']),
    nationality: (0, mysql_core_1.varchar)("nationality", { length: 50 }).default('Filipino'),
    bloodType: (0, mysql_core_1.varchar)("blood_type", { length: 5 }),
    heightCm: (0, mysql_core_1.decimal)("height_cm", { precision: 5, scale: 2 }),
    heightM: (0, mysql_core_1.decimal)("height_m", { precision: 4, scale: 2 }),
    weightKg: (0, mysql_core_1.decimal)("weight_kg", { precision: 5, scale: 2 }),
    phoneNumber: (0, mysql_core_1.varchar)("phone_number", { length: 20 }),
    address: (0, mysql_core_1.text)("address"),
    permanentAddress: (0, mysql_core_1.text)("permanent_address"),
    emergencyContact: (0, mysql_core_1.varchar)("emergency_contact", { length: 100 }),
    emergencyContactNumber: (0, mysql_core_1.varchar)("emergency_contact_number", { length: 20 }),
    umidNo: (0, mysql_core_1.varchar)("umid_no", { length: 50 }),
    philsysId: (0, mysql_core_1.varchar)("philsys_id", { length: 50 }),
    philhealthNumber: (0, mysql_core_1.varchar)("philhealth_number", { length: 20 }),
    philhealthNo: (0, mysql_core_1.varchar)("philhealth_no", { length: 50 }),
    pagibigNumber: (0, mysql_core_1.varchar)("pagibig_number", { length: 20 }),
    pagibigIdNo: (0, mysql_core_1.varchar)("pagibig_id_no", { length: 50 }),
    tinNumber: (0, mysql_core_1.varchar)("tin_number", { length: 20 }),
    tinNo: (0, mysql_core_1.varchar)("tin_no", { length: 50 }),
    gsisNumber: (0, mysql_core_1.varchar)("gsis_number", { length: 20 }),
    gsisIdNo: (0, mysql_core_1.varchar)("gsis_id_no", { length: 50 }),
    agencyEmployeeNo: (0, mysql_core_1.varchar)("agency_employee_no", { length: 50 }),
    salaryGrade: (0, mysql_core_1.varchar)("salary_grade", { length: 10 }),
    stepIncrement: (0, mysql_core_1.int)("step_increment").default(1),
    appointmentType: (0, mysql_core_1.mysqlEnum)("appointment_type", ['Permanent', 'Contractual', 'Casual', 'Job Order', 'Coterminous', 'Temporary', 'Contract of Service', 'JO', 'COS']),
    officeAddress: (0, mysql_core_1.text)("office_address"),
    station: (0, mysql_core_1.varchar)("station", { length: 100 }),
    positionTitle: (0, mysql_core_1.varchar)("position_title", { length: 100 }),
    itemNumber: (0, mysql_core_1.varchar)("item_number", { length: 50 }),
    positionId: (0, mysql_core_1.int)("position_id").references(function () { return plantilla_js_1.plantillaPositions.id; }, { onDelete: "set null" }),
    firstDayOfService: (0, mysql_core_1.date)("first_day_of_service", { mode: 'string' }),
    refreshToken: (0, mysql_core_1.text)("refresh_token"),
    twoFactorEnabled: (0, mysql_core_1.boolean)("two_factor_enabled").default(false),
    twoFactorOtp: (0, mysql_core_1.varchar)("two_factor_otp", { length: 6 }),
    twoFactorOtpExpires: (0, mysql_core_1.datetime)("two_factor_otp_expires", { mode: 'string' }),
    eligibilityType: (0, mysql_core_1.varchar)("eligibility_type", { length: 255 }),
    eligibilityNumber: (0, mysql_core_1.varchar)("eligibility_number", { length: 100 }),
    eligibilityDate: (0, mysql_core_1.date)("eligibility_date", { mode: 'string' }),
    highestEducation: (0, mysql_core_1.varchar)("highest_education", { length: 255 }),
    educationalBackground: (0, mysql_core_1.text)("educational_background"),
    schoolName: (0, mysql_core_1.varchar)("school_name", { length: 255 }),
    course: (0, mysql_core_1.varchar)("course", { length: 255 }),
    yearGraduated: (0, mysql_core_1.varchar)("year_graduated", { length: 10 }),
    yearsOfExperience: (0, mysql_core_1.varchar)("years_of_experience", { length: 50 }),
    experience: (0, mysql_core_1.text)("experience"),
    skills: (0, mysql_core_1.text)("skills"),
    placeOfBirth: (0, mysql_core_1.varchar)("place_of_birth", { length: 255 }),
    residentialAddress: (0, mysql_core_1.text)("residential_address"),
    residentialZipCode: (0, mysql_core_1.varchar)("residential_zip_code", { length: 50 }),
    permanentZipCode: (0, mysql_core_1.varchar)("permanent_zip_code", { length: 50 }),
    telephoneNo: (0, mysql_core_1.varchar)("telephone_no", { length: 50 }),
    mobileNo: (0, mysql_core_1.varchar)("mobile_no", { length: 50 }),
    originalAppointmentDate: (0, mysql_core_1.date)("original_appointment_date", { mode: 'string' }),
    lastPromotionDate: (0, mysql_core_1.date)("last_promotion_date", { mode: 'string' }),
    facebookUrl: (0, mysql_core_1.varchar)("facebook_url", { length: 255 }),
    linkedinUrl: (0, mysql_core_1.varchar)("linkedin_url", { length: 255 }),
    twitterHandle: (0, mysql_core_1.varchar)("twitter_handle", { length: 100 }),
    religion: (0, mysql_core_1.varchar)("religion", { length: 100 }),
    citizenship: (0, mysql_core_1.varchar)("citizenship", { length: 50 }).default('Filipino'),
    citizenshipType: (0, mysql_core_1.varchar)("citizenship_type", { length: 50 }),
    barangay: (0, mysql_core_1.varchar)("barangay", { length: 100 }),
    dutyType: (0, mysql_core_1.mysqlEnum)("duty_type", ['Standard', 'Irregular']).default('Standard'),
    dailyTargetHours: (0, mysql_core_1.decimal)("daily_target_hours", { precision: 4, scale: 2 }).default('8.00'),
    salaryBasis: (0, mysql_core_1.mysqlEnum)("salary_basis", ['Daily', 'Hourly']).default('Daily'),
    resHouseBlockLot: (0, mysql_core_1.varchar)("res_house_block_lot", { length: 150 }),
    resStreet: (0, mysql_core_1.varchar)("res_street", { length: 150 }),
    resSubdivision: (0, mysql_core_1.varchar)("res_subdivision", { length: 150 }),
    resBarangay: (0, mysql_core_1.varchar)("res_barangay", { length: 150 }),
    resCity: (0, mysql_core_1.varchar)("res_city", { length: 150 }),
    resProvince: (0, mysql_core_1.varchar)("res_province", { length: 150 }),
    permHouseBlockLot: (0, mysql_core_1.varchar)("perm_house_block_lot", { length: 150 }),
    permStreet: (0, mysql_core_1.varchar)("perm_street", { length: 150 }),
    permSubdivision: (0, mysql_core_1.varchar)("perm_subdivision", { length: 150 }),
    permBarangay: (0, mysql_core_1.varchar)("perm_barangay", { length: 150 }),
    permCity: (0, mysql_core_1.varchar)("perm_city", { length: 150 }),
    permProvince: (0, mysql_core_1.varchar)("perm_province", { length: 150 }),
    profileStatus: (0, mysql_core_1.mysqlEnum)("profile_status", ['Initial', 'Complete']).default('Initial'),
    rightThumbmarkUrl: (0, mysql_core_1.varchar)("right_thumbmark_url", { length: 500 }),
    ctcNo: (0, mysql_core_1.varchar)("ctc_no", { length: 50 }),
    ctcIssuedAt: (0, mysql_core_1.varchar)("ctc_issued_at", { length: 255 }),
    ctcIssuedDate: (0, mysql_core_1.date)("ctc_issued_date", { mode: 'string' }),
    loginAttempts: (0, mysql_core_1.int)("login_attempts").default(0),
    lockUntil: (0, mysql_core_1.datetime)("lock_until", { mode: 'string' }),
}, function (table) { return [
    (0, mysql_core_1.foreignKey)({
        columns: [table.managerId],
        foreignColumns: [table.id],
        name: "fk_manager"
    }).onDelete("set null"),
    (0, mysql_core_1.primaryKey)({ columns: [table.id], name: "authentication_id" }),
    (0, mysql_core_1.unique)("email").on(table.email),
    (0, mysql_core_1.unique)("employee_id").on(table.employeeId),
    (0, mysql_core_1.unique)("google_id").on(table.googleId),
]; });
exports.googleCalendarTokens = (0, mysql_core_1.mysqlTable)("google_calendar_tokens", {
    userId: (0, mysql_core_1.int)("user_id").notNull().references(function () { return exports.authentication.id; }, { onDelete: "cascade" }),
    accessToken: (0, mysql_core_1.text)("access_token").notNull(),
    refreshToken: (0, mysql_core_1.text)("refresh_token").notNull(),
    tokenExpiry: (0, mysql_core_1.datetime)("token_expiry", { mode: 'string' }).notNull(),
    syncEnabled: (0, mysql_core_1.boolean)("sync_enabled").default(true),
    calendarId: (0, mysql_core_1.varchar)("calendar_id", { length: 255 }).default('primary'),
    lastSync: (0, mysql_core_1.datetime)("last_sync", { mode: 'string' }).default((0, drizzle_orm_1.sql)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["(CURRENT_TIMESTAMP)"], ["(CURRENT_TIMESTAMP)"])))),
    createdAt: (0, mysql_core_1.timestamp)("created_at", { mode: 'string' }).defaultNow(),
    updatedAt: (0, mysql_core_1.timestamp)("updated_at", { mode: 'string' }).defaultNow().onUpdateNow(),
}, function (table) { return [
    (0, mysql_core_1.primaryKey)({ columns: [table.userId], name: "google_calendar_tokens_user_id" }),
]; });
exports.socialConnections = (0, mysql_core_1.mysqlTable)("social_connections", {
    id: (0, mysql_core_1.int)("id").autoincrement().notNull(),
    userId: (0, mysql_core_1.int)("user_id").notNull().references(function () { return exports.authentication.id; }, { onDelete: "cascade" }),
    provider: (0, mysql_core_1.mysqlEnum)("provider", ['facebook', 'jobstreet']).notNull(),
    providerUserId: (0, mysql_core_1.varchar)("provider_user_id", { length: 100 }).notNull(),
    providerUserName: (0, mysql_core_1.varchar)("provider_user_name", { length: 255 }),
    accessToken: (0, mysql_core_1.text)("access_token"),
    refreshToken: (0, mysql_core_1.text)("refresh_token"),
    expiresAt: (0, mysql_core_1.datetime)("expires_at", { mode: 'string' }),
    metadata: (0, mysql_core_1.json)("metadata"),
    createdAt: (0, mysql_core_1.timestamp)("created_at", { mode: 'string' }).defaultNow(),
    updatedAt: (0, mysql_core_1.timestamp)("updated_at", { mode: 'string' }).defaultNow().onUpdateNow(),
}, function (table) { return [
    (0, mysql_core_1.primaryKey)({ columns: [table.id], name: "social_connections_id" }),
    (0, mysql_core_1.unique)("unique_user_provider").on(table.userId, table.provider),
]; });
var templateObject_1;
