import { mysqlTable, varchar, int, date, timestamp, decimal, text, mysqlEnum, datetime, unique, tinyint, foreignKey, primaryKey, json } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';
import { departments } from './hr.js';
import { plantillaPositions } from './plantilla.js';

export const authentication = mysqlTable("authentication", {
	id: int().autoincrement().notNull(),
	firstName: varchar("first_name", { length: 100 }).notNull(),
	lastName: varchar("last_name", { length: 100 }).notNull(),
	suffix: varchar("suffix", { length: 20 }),
	email: varchar({ length: 255 }).notNull(),
	role: varchar({ length: 50 }).notNull(),
	department: varchar({ length: 100 }), // Made nullable to match controller usage
	departmentId: int("department_id").references(() => departments.id, { onDelete: "set null" } ),
	employeeId: varchar("employee_id", { length: 50 }).notNull(),
	rfidCardUid: varchar("rfid_card_uid", { length: 50 }),
	passwordHash: varchar("password_hash", { length: 255 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	isVerified: tinyint("is_verified").default(0),
	verificationToken: varchar("verification_token", { length: 255 }),
	resetPasswordToken: varchar("reset_password_token", { length: 255 }),
	resetPasswordExpires: datetime("reset_password_expires", { mode: 'string'}),
	googleId: varchar("google_id", { length: 255 }),
	avatarUrl: varchar("avatar_url", { length: 500 }),
	jobTitle: varchar("job_title", { length: 100 }),
	employmentStatus: mysqlEnum("employment_status", ['Active','Probationary','Terminated','Resigned','On Leave','Suspended','Verbal Warning','Written Warning','Show Cause']).default('Active'),
	employmentType: varchar("employment_type", { length: 50 }).default('Probationary'),
	dateHired: date("date_hired", { mode: 'string' }),
	contractEndDate: date("contract_end_date", { mode: 'string' }),
	regularizationDate: date("regularization_date", { mode: 'string' }),
	isRegular: tinyint("is_regular").default(0),
	managerId: int("manager_id"),
	birthDate: date("birth_date", { mode: 'string' }),
	gender: mysqlEnum(['Male','Female']),
	civilStatus: mysqlEnum("civil_status", ['Single','Married','Widowed','Separated','Annulled']),
	nationality: varchar({ length: 50 }).default('Filipino'),
	bloodType: varchar("blood_type", { length: 5 }),
	heightCm: decimal("height_cm", { precision: 5, scale: 2 }),
	weightKg: decimal("weight_kg", { precision: 5, scale: 2 }),
	phoneNumber: varchar("phone_number", { length: 20 }),
	address: text(),
	permanentAddress: text("permanent_address"),
	emergencyContact: varchar("emergency_contact", { length: 100 }),
	emergencyContactNumber: varchar("emergency_contact_number", { length: 20 }),
	umidNo: varchar("umid_no", { length: 50 }),
	philhealthNumber: varchar("philhealth_number", { length: 20 }),
	pagibigNumber: varchar("pagibig_number", { length: 20 }),
	tinNumber: varchar("tin_number", { length: 20 }),
	gsisNumber: varchar("gsis_number", { length: 20 }),
	salaryGrade: varchar("salary_grade", { length: 10 }),
	stepIncrement: int("step_increment").default(1),
	appointmentType: mysqlEnum("appointment_type", ['Permanent','Contractual','Casual','Job Order','Coterminous','Temporary']),
	officeAddress: text("office_address"),
	station: varchar({ length: 100 }),
	positionTitle: varchar("position_title", { length: 100 }),
	itemNumber: varchar("item_number", { length: 50 }),
	positionId: int("position_id").references(() => plantillaPositions.id, { onDelete: "set null" } ),

	firstDayOfService: date("first_day_of_service", { mode: 'string' }),
	supervisor: varchar({ length: 100 }),
	refreshToken: text("refresh_token"),
	twoFactorEnabled: tinyint("two_factor_enabled").default(0),
	twoFactorOtp: varchar("two_factor_otp", { length: 6 }),
	twoFactorOtpExpires: datetime("two_factor_otp_expires", { mode: 'string'}),
	eligibilityType: varchar("eligibility_type", { length: 255 }),
	eligibilityNumber: varchar("eligibility_number", { length: 100 }),
	eligibilityDate: date("eligibility_date", { mode: 'string' }),
	highestEducation: varchar("highest_education", { length: 255 }),
	educationalBackground: text("educational_background"),
	yearsOfExperience: int("years_of_experience").default(0),
	placeOfBirth: varchar("place_of_birth", { length: 255 }),
	dateOfBirth: date("date_of_birth", { mode: 'string' }),
	heightM: decimal("height_m", { precision: 4, scale: 2 }),
	gsisIdNo: varchar("gsis_id_no", { length: 50 }),
	pagibigIdNo: varchar("pagibig_id_no", { length: 50 }),
	philhealthNo: varchar("philhealth_no", { length: 50 }),
	philsysId: varchar("philsys_id", { length: 50 }),
	tinNo: varchar("tin_no", { length: 50 }),
	agencyEmployeeNo: varchar("agency_employee_no", { length: 50 }),
	citizenship: varchar({ length: 50 }).default('Filipino'),
	citizenshipType: mysqlEnum("citizenship_type", ['By Birth','By Naturalization']).default('By Birth'),
	dualCitizenshipCountry: varchar("dual_citizenship_country", { length: 100 }),
	residentialAddress: text("residential_address"),
	residentialZipCode: varchar("residential_zip_code", { length: 50 }),
	permanentZipCode: varchar("permanent_zip_code", { length: 50 }),
	telephoneNo: varchar("telephone_no", { length: 50 }),
	mobileNo: varchar("mobile_no", { length: 50 }),
	originalAppointmentDate: date("original_appointment_date", { mode: 'string' }),
	lastPromotionDate: date("last_promotion_date", { mode: 'string' }),
	middleName: varchar("middle_name", { length: 100 }),
	facebookUrl: varchar("facebook_url", { length: 255 }),
	linkedinUrl: varchar("linkedin_url", { length: 255 }),
	twitterHandle: varchar("twitter_handle", { length: 100 }),
	dutyType: mysqlEnum("duty_type", ['Standard','Irregular']).default('Standard'),
	dailyTargetHours: decimal("daily_target_hours", { precision: 4, scale: 2 }).default('8.00'),
	salaryBasis: mysqlEnum("salary_basis", ['Daily','Hourly']).default('Daily'),
	loginAttempts: int("login_attempts").default(0),
	lockUntil: datetime("lock_until", { mode: 'string'}),
},
(table) => [
	foreignKey({
			columns: [table.managerId],
			foreignColumns: [table.id],
			name: "fk_manager"
		}).onDelete("set null"),
	primaryKey({ columns: [table.id], name: "authentication_id"}),
	unique("email").on(table.email),
	unique("employee_id").on(table.employeeId),
	unique("google_id").on(table.googleId),
	unique("rfid_card_uid").on(table.rfidCardUid),
]);

export const googleCalendarTokens = mysqlTable("google_calendar_tokens", {
	userId: int("user_id").notNull().references(() => authentication.id, { onDelete: "cascade" } ),
	accessToken: text("access_token").notNull(),
	refreshToken: text("refresh_token").notNull(),
	tokenExpiry: datetime("token_expiry", { mode: 'string'}).notNull(),
	syncEnabled: tinyint("sync_enabled").default(1),
	calendarId: varchar("calendar_id", { length: 255 }).default('primary'),
	lastSync: datetime("last_sync", { mode: 'string'}).default(sql`(CURRENT_TIMESTAMP)`),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.userId], name: "google_calendar_tokens_user_id"}),
]);

export const socialConnections = mysqlTable("social_connections", {
	id: int().autoincrement().notNull(),
	userId: int("user_id").notNull().references(() => authentication.id, { onDelete: "cascade" } ),
	provider: mysqlEnum(['facebook','jobstreet']).notNull(),
	providerUserId: varchar("provider_user_id", { length: 100 }).notNull(),
	providerUserName: varchar("provider_user_name", { length: 255 }),
	accessToken: text("access_token"),
	refreshToken: text("refresh_token"),
	expiresAt: datetime("expires_at", { mode: 'string'}),
	metadata: json(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "social_connections_id"}),
	unique("unique_user_provider").on(table.userId, table.provider),
]);
