"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.recruitmentSecurityLogs = exports.recruitmentEmailTemplates = exports.recruitmentApplicants = exports.recruitmentJobs = exports.contactInquiries = exports.chatMessages = exports.chatConversations = void 0;
var mysql_core_1 = require("drizzle-orm/mysql-core");
var auth_js_1 = require("./auth.js");
exports.chatConversations = (0, mysql_core_1.mysqlTable)("chat_conversations", {
    id: (0, mysql_core_1.int)("id").autoincrement().notNull(),
    applicantName: (0, mysql_core_1.varchar)("applicant_name", { length: 100 }).notNull(),
    applicantEmail: (0, mysql_core_1.varchar)("applicant_email", { length: 255 }).notNull(),
    status: (0, mysql_core_1.mysqlEnum)("status", ['Active', 'Closed', 'Archived']).default('Active'),
    createdAt: (0, mysql_core_1.timestamp)("created_at", { mode: 'string' }).defaultNow(),
    updatedAt: (0, mysql_core_1.timestamp)("updated_at", { mode: 'string' }).defaultNow().onUpdateNow(),
}, function (table) { return [
    (0, mysql_core_1.index)("idx_applicant_email").on(table.applicantEmail),
    (0, mysql_core_1.index)("idx_status").on(table.status),
    (0, mysql_core_1.primaryKey)({ columns: [table.id], name: "chat_conversations_id" }),
]; });
exports.chatMessages = (0, mysql_core_1.mysqlTable)("chat_messages", {
    id: (0, mysql_core_1.int)("id").autoincrement().notNull(),
    conversationId: (0, mysql_core_1.int)("conversation_id").notNull().references(function () { return exports.chatConversations.id; }, { onDelete: "cascade" }),
    senderType: (0, mysql_core_1.mysqlEnum)("sender_type", ['Applicant', 'Administrator']).notNull(),
    senderId: (0, mysql_core_1.int)("sender_id"),
    message: (0, mysql_core_1.text)("message").notNull(),
    isRead: (0, mysql_core_1.boolean)("is_read").default(false),
    createdAt: (0, mysql_core_1.timestamp)("created_at", { mode: 'string' }).defaultNow(),
}, function (table) { return [
    (0, mysql_core_1.index)("idx_conversation").on(table.conversationId),
    (0, mysql_core_1.index)("idx_is_read").on(table.isRead),
    (0, mysql_core_1.primaryKey)({ columns: [table.id], name: "chat_messages_id" }),
]; });
exports.contactInquiries = (0, mysql_core_1.mysqlTable)("contact_inquiries", {
    id: (0, mysql_core_1.int)("id").autoincrement().notNull(),
    firstName: (0, mysql_core_1.varchar)("first_name", { length: 100 }).notNull(),
    lastName: (0, mysql_core_1.varchar)("last_name", { length: 100 }).notNull(),
    email: (0, mysql_core_1.varchar)("email", { length: 255 }).notNull(),
    message: (0, mysql_core_1.text)("message").notNull(),
    status: (0, mysql_core_1.mysqlEnum)("status", ['Pending', 'Read', 'Replied', 'Archived']).default('Pending'),
    adminNotes: (0, mysql_core_1.text)("admin_notes"),
    createdAt: (0, mysql_core_1.timestamp)("created_at", { mode: 'string' }).defaultNow(),
    updatedAt: (0, mysql_core_1.timestamp)("updated_at", { mode: 'string' }).defaultNow().onUpdateNow(),
}, function (table) { return [
    (0, mysql_core_1.index)("idx_status").on(table.status),
    (0, mysql_core_1.index)("idx_email").on(table.email),
    (0, mysql_core_1.index)("idx_created_at").on(table.createdAt),
    (0, mysql_core_1.primaryKey)({ columns: [table.id], name: "contact_inquiries_id" }),
]; });
exports.recruitmentJobs = (0, mysql_core_1.mysqlTable)("recruitment_jobs", {
    id: (0, mysql_core_1.int)("id").autoincrement().notNull(),
    title: (0, mysql_core_1.varchar)("title", { length: 255 }).notNull(),
    department: (0, mysql_core_1.varchar)("department", { length: 100 }).notNull(),
    jobDescription: (0, mysql_core_1.text)("job_description").notNull(),
    requirements: (0, mysql_core_1.text)("requirements"),
    location: (0, mysql_core_1.varchar)("location", { length: 100 }).default('Main Office'),
    employmentType: (0, mysql_core_1.mysqlEnum)("employment_type", ['Full-time', 'Part-time', 'Contractual', 'Job Order', 'Coterminous', 'Temporary', 'Probationary', 'Casual', 'Permanent']).default('Full-time'),
    dutyType: (0, mysql_core_1.mysqlEnum)("duty_type", ['Standard', 'Irregular']).default('Standard'),
    status: (0, mysql_core_1.mysqlEnum)("status", ['Open', 'Closed', 'On Hold']).default('Open'),
    applicationEmail: (0, mysql_core_1.varchar)("application_email", { length: 255 }),
    postedBy: (0, mysql_core_1.int)("posted_by"),
    postedAt: (0, mysql_core_1.datetime)("posted_at", { mode: 'string' }),
    fbPostId: (0, mysql_core_1.varchar)("fb_post_id", { length: 100 }),
    linkedinPostId: (0, mysql_core_1.varchar)("linkedin_post_id", { length: 255 }),
    createdAt: (0, mysql_core_1.timestamp)("created_at", { mode: 'string' }).defaultNow(),
    updatedAt: (0, mysql_core_1.timestamp)("updated_at", { mode: 'string' }).defaultNow().onUpdateNow(),
    attachmentPath: (0, mysql_core_1.varchar)("attachment_path", { length: 255 }),
    requireCivilService: (0, mysql_core_1.boolean)("require_civil_service").default(false),
    requireGovernmentIds: (0, mysql_core_1.boolean)("require_government_ids").default(false),
    requireEducationExperience: (0, mysql_core_1.boolean)("require_education_experience").default(false),
}, function (table) { return [
    (0, mysql_core_1.primaryKey)({ columns: [table.id], name: "recruitment_jobs_id" }),
]; });
exports.recruitmentApplicants = (0, mysql_core_1.mysqlTable)("recruitment_applicants", {
    id: (0, mysql_core_1.int)("id").autoincrement().notNull(),
    jobId: (0, mysql_core_1.int)("job_id").references(function () { return exports.recruitmentJobs.id; }, { onDelete: "set null" }),
    firstName: (0, mysql_core_1.varchar)("first_name", { length: 100 }).notNull(),
    lastName: (0, mysql_core_1.varchar)("last_name", { length: 100 }).notNull(),
    email: (0, mysql_core_1.varchar)("email", { length: 100 }).notNull(),
    phoneNumber: (0, mysql_core_1.varchar)("phone_number", { length: 20 }),
    resumePath: (0, mysql_core_1.varchar)("resume_path", { length: 255 }),
    photoPath: (0, mysql_core_1.varchar)("photo_path", { length: 255 }),
    status: (0, mysql_core_1.mysqlEnum)("status", ['Applied', 'Screening', 'Interview', 'Offer', 'Hired', 'Rejected']).default('Applied'),
    source: (0, mysql_core_1.mysqlEnum)("source", ['web', 'email']).default('web'),
    emailSubject: (0, mysql_core_1.varchar)("email_subject", { length: 255 }),
    emailReceivedAt: (0, mysql_core_1.datetime)("email_received_at", { mode: 'string' }),
    createdAt: (0, mysql_core_1.timestamp)("created_at", { mode: 'string' }).defaultNow(),
    stage: (0, mysql_core_1.mysqlEnum)("stage", ['Applied', 'Screening', 'Initial Interview', 'Final Interview', 'Offer', 'Hired', 'Rejected']).default('Applied'),
    interviewDate: (0, mysql_core_1.datetime)("interview_date", { mode: 'string' }),
    interviewLink: (0, mysql_core_1.varchar)("interview_link", { length: 500 }),
    interviewPlatform: (0, mysql_core_1.mysqlEnum)("interview_platform", ['Jitsi Meet', 'Google Meet', 'Zoom', 'Other']).default('Google Meet'),
    interviewNotes: (0, mysql_core_1.text)("interview_notes"),
    interviewerId: (0, mysql_core_1.int)("interviewer_id").references(function () { return auth_js_1.authentication.id; }, { onDelete: "set null" }),
    middleName: (0, mysql_core_1.varchar)("middle_name", { length: 100 }),
    suffix: (0, mysql_core_1.varchar)("suffix", { length: 10 }),
    zipCode: (0, mysql_core_1.varchar)("zip_code", { length: 10 }),
    birthDate: (0, mysql_core_1.datetime)("birth_date", { mode: 'string' }),
    birthPlace: (0, mysql_core_1.varchar)("birth_place", { length: 255 }),
    sex: (0, mysql_core_1.mysqlEnum)("sex", ['Male', 'Female']),
    civilStatus: (0, mysql_core_1.mysqlEnum)("civil_status", ['Single', 'Married', 'Widowed', 'Separated', 'Annulled']),
    height: (0, mysql_core_1.varchar)("height", { length: 20 }),
    weight: (0, mysql_core_1.varchar)("weight", { length: 20 }),
    bloodType: (0, mysql_core_1.varchar)("blood_type", { length: 10 }),
    gsisNo: (0, mysql_core_1.varchar)("gsis_no", { length: 50 }),
    pagibigNo: (0, mysql_core_1.varchar)("pagibig_no", { length: 50 }),
    philhealthNo: (0, mysql_core_1.varchar)("philhealth_no", { length: 50 }),
    umidNo: (0, mysql_core_1.varchar)("umid_no", { length: 50 }),
    philsysId: (0, mysql_core_1.varchar)("philsys_id", { length: 50 }),
    tinNo: (0, mysql_core_1.varchar)("tin_no", { length: 50 }),
    eligibility: (0, mysql_core_1.text)("eligibility"),
    eligibilityType: (0, mysql_core_1.varchar)("eligibility_type", { length: 100 }),
    eligibilityDate: (0, mysql_core_1.datetime)("eligibility_date", { mode: 'string' }),
    eligibilityRating: (0, mysql_core_1.varchar)("eligibility_rating", { length: 50 }),
    eligibilityPlace: (0, mysql_core_1.varchar)("eligibility_place", { length: 255 }),
    licenseNo: (0, mysql_core_1.varchar)("license_no", { length: 50 }),
    eligibilityPath: (0, mysql_core_1.varchar)("eligibility_path", { length: 255 }),
    totalExperienceYears: (0, mysql_core_1.int)("total_experience_years"),
    address: (0, mysql_core_1.text)("address"),
    permanentAddress: (0, mysql_core_1.text)("permanent_address"),
    permanentZipCode: (0, mysql_core_1.varchar)("permanent_zip_code", { length: 10 }),
    education: (0, mysql_core_1.text)("education"),
    schoolName: (0, mysql_core_1.varchar)("school_name", { length: 255 }),
    course: (0, mysql_core_1.varchar)("course", { length: 255 }),
    yearGraduated: (0, mysql_core_1.varchar)("year_graduated", { length: 10 }),
    experience: (0, mysql_core_1.text)("experience"),
    skills: (0, mysql_core_1.text)("skills"),
    emergencyContact: (0, mysql_core_1.varchar)("emergency_contact", { length: 255 }),
    emergencyContactNumber: (0, mysql_core_1.varchar)("emergency_contact_number", { length: 20 }),
    hiredDate: (0, mysql_core_1.datetime)("hired_date", { mode: 'string' }),
    isMeycauayanResident: (0, mysql_core_1.boolean)("is_meycauayan_resident").default(false),
}, function (table) { return [
    (0, mysql_core_1.index)("job_id").on(table.jobId),
    (0, mysql_core_1.primaryKey)({ columns: [table.id], name: "recruitment_applicants_id" }),
]; });
exports.recruitmentEmailTemplates = (0, mysql_core_1.mysqlTable)("recruitment_email_templates", {
    id: (0, mysql_core_1.int)("id").autoincrement().notNull(),
    stageName: (0, mysql_core_1.varchar)("stage_name", { length: 50 }).notNull(),
    subjectTemplate: (0, mysql_core_1.varchar)("subject_template", { length: 255 }).notNull(),
    bodyTemplate: (0, mysql_core_1.text)("body_template").notNull(),
    availableVariables: (0, mysql_core_1.text)("available_variables"),
    updatedAt: (0, mysql_core_1.timestamp)("updated_at", { mode: 'string' }).defaultNow().onUpdateNow(),
}, function (table) { return [
    (0, mysql_core_1.primaryKey)({ columns: [table.id], name: "recruitment_email_templates_id" }),
    (0, mysql_core_1.unique)("stage_name").on(table.stageName),
]; });
exports.recruitmentSecurityLogs = (0, mysql_core_1.mysqlTable)("recruitment_security_logs", {
    id: (0, mysql_core_1.int)("id").autoincrement().notNull(),
    jobId: (0, mysql_core_1.int)("job_id"),
    firstName: (0, mysql_core_1.varchar)("first_name", { length: 100 }),
    lastName: (0, mysql_core_1.varchar)("last_name", { length: 100 }),
    email: (0, mysql_core_1.varchar)("email", { length: 255 }),
    violationType: (0, mysql_core_1.varchar)("violation_type", { length: 100 }), // e.g., 'Identity Fraud', 'Duplicate', 'Spam Bot'
    details: (0, mysql_core_1.text)("details"),
    ipAddress: (0, mysql_core_1.varchar)("ip_address", { length: 45 }),
    createdAt: (0, mysql_core_1.timestamp)("created_at", { mode: 'string' }).defaultNow(),
}, function (table) { return [
    (0, mysql_core_1.index)("idx_violation").on(table.violationType),
    (0, mysql_core_1.primaryKey)({ columns: [table.id], name: "recruitment_security_logs_id" }),
]; });
