import { mysqlTable, varchar, int, text, mysqlEnum, datetime, boolean, primaryKey, timestamp, index, unique, decimal } from 'drizzle-orm/mysql-core';
import { authentication } from './auth.js';

export const chatConversations = mysqlTable("chat_conversations", {
	id: int("id").autoincrement().notNull(),
	applicantName: varchar("applicant_name", { length: 100 }).notNull(),
	applicantEmail: varchar("applicant_email", { length: 255 }).notNull(),
	status: mysqlEnum("status", ['Active','Closed','Archived']).default('Active'),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow(),
},
(table) => [
	index("idx_applicant_email").on(table.applicantEmail),
	index("idx_status").on(table.status),
	primaryKey({ columns: [table.id], name: "chat_conversations_id"}),
]);

export const chatMessages = mysqlTable("chat_messages", {
	id: int("id").autoincrement().notNull(),
	conversationId: int("conversation_id").notNull().references(() => chatConversations.id, { onDelete: "cascade" } ),
	senderType: mysqlEnum("sender_type", ['Applicant','Administrator']).notNull(),
	senderId: int("sender_id"),
	message: text("message").notNull(),
	isRead: boolean("is_read").default(false),
	isEdited: boolean("is_edited").default(false),
	isDeletedForEveryone: boolean("is_deleted_for_everyone").default(false),
	deletedByApplicant: boolean("deleted_by_applicant").default(false),
	deletedByAdministrator: boolean("deleted_by_administrator").default(false),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
},
(table) => [
	index("idx_conversation").on(table.conversationId),
	index("idx_is_read").on(table.isRead),
	primaryKey({ columns: [table.id], name: "chat_messages_id"}),
]);

export const contactInquiries = mysqlTable("contact_inquiries", {
	id: int("id").autoincrement().notNull(),
	firstName: varchar("first_name", { length: 100 }).notNull(),
	lastName: varchar("last_name", { length: 100 }).notNull(),
	email: varchar("email", { length: 255 }).notNull(),
	message: text("message").notNull(),
	status: mysqlEnum("status", ['Pending','Read','Replied','Archived']).default('Pending'),
	adminNotes: text("admin_notes"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow(),
},
(table) => [
	index("idx_status").on(table.status),
	index("idx_email").on(table.email),
	index("idx_created_at").on(table.createdAt),
	primaryKey({ columns: [table.id], name: "contact_inquiries_id"}),
]);

export const recruitmentJobs = mysqlTable("recruitment_jobs", {
	id: int("id").autoincrement().notNull(),
	title: varchar("title", { length: 255 }).notNull(),
	department: varchar("department", { length: 100 }).notNull(),
	jobDescription: text("job_description").notNull(),
	requirements: text("requirements"),
	location: varchar("location", { length: 100 }).default('Main Office'),
	employmentType: mysqlEnum("employment_type", ['Full-time','Part-time','Contractual','Job Order','Coterminous','Temporary','Probationary','Casual','Permanent', 'Contract of Service', 'JO', 'COS']).default('Full-time'),
	dutyType: mysqlEnum("duty_type", ['Standard','Irregular']).default('Standard'),
	status: mysqlEnum("status", ['Open','Closed','On Hold']).default('Open'),
	applicationEmail: varchar("application_email", { length: 255 }),
	postedBy: int("posted_by"),
	postedAt: datetime("posted_at", { mode: 'string'}),
	fbPostId: varchar("fb_post_id", { length: 100 }),
	linkedinPostId: varchar("linkedin_post_id", { length: 255 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow(),
	attachmentPath: varchar("attachment_path", { length: 255 }),
	requireCivilService: boolean("require_civil_service").default(false),
	requireGovernmentIds: boolean("require_government_ids").default(false),
	requireEducationExperience: boolean("require_education_experience").default(false),
	education: text("education"),
	experience: text("experience"),
	training: text("training"),
	eligibility: text("eligibility"),
	otherQualifications: text("other_qualifications"),
},
(table) => [
	primaryKey({ columns: [table.id], name: "recruitment_jobs_id"}),
]);

export const recruitmentApplicants = mysqlTable("recruitment_applicants", {
	id: int("id").autoincrement().notNull(),
	jobId: int("job_id").references(() => recruitmentJobs.id, { onDelete: "set null" } ),
	firstName: varchar("first_name", { length: 100 }).notNull(),
	lastName: varchar("last_name", { length: 100 }).notNull(),
	email: varchar("email", { length: 100 }).notNull(),
	phoneNumber: varchar("phone_number", { length: 20 }),
	resumePath: varchar("resume_path", { length: 255 }),
	photoPath: varchar("photo_path", { length: 255 }),
	status: mysqlEnum("status", ['Applied','Screening','Interview','Offer','Hired','Rejected']).default('Applied'),
	source: mysqlEnum("source", ['web','email']).default('web'),
	emailSubject: varchar("email_subject", { length: 255 }),
	emailReceivedAt: datetime("email_received_at", { mode: 'string'}),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	stage: mysqlEnum("stage", ['Applied','Screening','Initial Interview','Final Interview','Offer','Hired','Rejected']).default('Applied'),
	interviewDate: datetime("interview_date", { mode: 'string'}),
	interviewLink: varchar("interview_link", { length: 500 }),
	interviewPlatform: mysqlEnum("interview_platform", ['Jitsi Meet', 'Google Meet','Zoom','Other']).default('Google Meet'),
	interviewNotes: text("interview_notes"),
	interviewerId: int("interviewer_id").references(() => authentication.id, { onDelete: "set null" } ),
	middleName: varchar("middle_name", { length: 100 }),
	suffix: varchar("suffix", { length: 10 }),
	zipCode: varchar("zip_code", { length: 10 }),
	birthDate: datetime("birth_date", { mode: 'string'}),
	birthPlace: varchar("birth_place", { length: 255 }),
	sex: mysqlEnum("sex", ['Male', 'Female']),
	civilStatus: mysqlEnum("civil_status", ['Single', 'Married', 'Widowed', 'Separated', 'Annulled']),
	height: varchar("height", { length: 20 }),
	weight: varchar("weight", { length: 20 }),
	bloodType: varchar("blood_type", { length: 10 }),
	gsisNumber: varchar("gsis_no", { length: 50 }),
	pagibigNumber: varchar("pagibig_no", { length: 50 }),
	philhealthNumber: varchar("philhealth_no", { length: 50 }),
	umidNumber: varchar("umid_no", { length: 50 }),
	philsysId: varchar("philsys_id", { length: 50 }),
	tinNumber: varchar("tin_no", { length: 50 }),
	eligibility: text("eligibility"),
	eligibilityType: varchar("eligibility_type", { length: 100 }),
	eligibilityDate: datetime("eligibility_date", { mode: 'string'}),
	eligibilityRating: varchar("eligibility_rating", { length: 50 }),
	eligibilityPlace: varchar("eligibility_place", { length: 255 }),
	licenseNo: varchar("license_no", { length: 50 }),
	eligibilityPath: varchar("eligibility_path", { length: 255 }),
	totalExperienceYears: int("total_experience_years"),
	address: text("address"),
	permanentAddress: text("permanent_address"),
	permanentZipCode: varchar("permanent_zip_code", { length: 10 }),
	educationalBackground: text("educational_background"),
	schoolName: varchar("school_name", { length: 255 }),
	course: varchar("course", { length: 255 }),
	yearGraduated: varchar("year_graduated", { length: 10 }),
	experience: text("experience"),
	training: text("training"),
	skills: text("skills"),
	emergencyContact: varchar("emergency_contact", { length: 255 }),
	emergencyContactNumber: varchar("emergency_contact_number", { length: 20 }),
	telephoneNumber: varchar("telephone_number", { length: 20 }),
	facebookUrl: varchar("facebook_url", { length: 255 }),
	linkedinUrl: varchar("linkedin_url", { length: 255 }),
	twitterHandle: varchar("twitter_handle", { length: 255 }),
	agencyEmployeeNo: varchar("agency_employee_no", { length: 50 }),
	nationality: varchar("nationality", { length: 100 }).default('Filipino'),
	photo1x1Path: varchar("photo1x1_path", { length: 255 }),
	hiredDate: datetime("hired_date", { mode: 'string'}),
	startDate: datetime("start_date", { mode: 'string'}),
	isConfirmed: boolean("is_confirmed").default(false),
	isRegistered: boolean("is_registered").default(false),
	registeredEmployeeId: varchar("registered_employee_id", { length: 50 }),
	isMeycauayanResident: boolean("is_meycauayan_resident").default(false),
	isEmailVerified: boolean("is_email_verified").default(false),
	verificationToken: varchar("verification_token", { length: 6 }),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow(),
	resHouseBlockLot: varchar("res_house_block_lot", { length: 100 }),
	resStreet: varchar("res_street", { length: 100 }),
	resSubdivision: varchar("res_subdivision", { length: 100 }),
	resBarangay: varchar("res_barangay", { length: 100 }),
	resCity: varchar("res_city", { length: 100 }),
	resProvince: varchar("res_province", { length: 100 }),
	resRegion: varchar("res_region", { length: 100 }),
	permHouseBlockLot: varchar("perm_house_block_lot", { length: 100 }),
	permStreet: varchar("perm_street", { length: 100 }),
	permSubdivision: varchar("perm_subdivision", { length: 100 }),
	permBarangay: varchar("perm_barangay", { length: 100 }),
	permCity: varchar("perm_city", { length: 100 }),
	permProvince: varchar("perm_province", { length: 100 }),
	permRegion: varchar("perm_region", { length: 100 }),
	citizenshipType: varchar("citizenship_type", { length: 50 }),
	dualCountry: varchar("dual_country", { length: 100 }),


},
(table) => [
	index("job_id").on(table.jobId),
	primaryKey({ columns: [table.id], name: "recruitment_applicants_id"}),
	unique("email_unique").on(table.email),
	unique("umid_no_unique").on(table.umidNumber),
	unique("philsys_id_unique").on(table.philsysId),
	unique("philhealth_no_unique").on(table.philhealthNumber),
	unique("pagibig_no_unique").on(table.pagibigNumber),
	unique("tin_no_unique").on(table.tinNumber),
	unique("gsis_no_unique").on(table.gsisNumber),
]);

export const applicantEducation = mysqlTable("applicant_education", {
	id: int("id").autoincrement().notNull(),
	applicantId: int("applicant_id").notNull().references(() => recruitmentApplicants.id, { onDelete: "cascade" } ),
	level: mysqlEnum("level", ['Elementary','Secondary','Vocational','College','Graduate Studies']).notNull(),
	schoolName: varchar("school_name", { length: 255 }).notNull(),
	degreeCourse: varchar("degree_course", { length: 255 }),
	yearGraduated: varchar("year_graduated", { length: 10 }),
	unitsEarned: varchar("units_earned", { length: 50 }),
	dateFrom: varchar("date_from", { length: 20 }),
	dateTo: varchar("date_to", { length: 20 }),
	honors: varchar("honors", { length: 255 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
},
(table) => [
	index("idx_app_edu_id").on(table.applicantId),
	primaryKey({ columns: [table.id], name: "applicant_education_id"}),
]);

export const applicantExperience = mysqlTable("applicant_experience", {
	id: int("id").autoincrement().notNull(),
	applicantId: int("applicant_id").notNull().references(() => recruitmentApplicants.id, { onDelete: "cascade" } ),
	dateFrom: varchar("date_from", { length: 20 }).notNull(),
	dateTo: varchar("date_to", { length: 20 }),
	positionTitle: varchar("position_title", { length: 255 }).notNull(),
	companyName: varchar("company_name", { length: 255 }).notNull(),
	monthlySalary: decimal("monthly_salary", { precision: 12, scale: 2 }),
	salaryGrade: varchar("salary_grade", { length: 20 }),
	appointmentStatus: varchar("appointment_status", { length: 50 }),
	isGovernment: boolean("is_government").default(false),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
},
(table) => [
	index("idx_app_exp_id").on(table.applicantId),
	primaryKey({ columns: [table.id], name: "applicant_experience_id"}),
]);

export const applicantTraining = mysqlTable("applicant_training", {
	id: int("id").autoincrement().notNull(),
	applicantId: int("applicant_id").notNull().references(() => recruitmentApplicants.id, { onDelete: "cascade" } ),
	title: varchar("title", { length: 255 }).notNull(),
	dateFrom: varchar("date_from", { length: 20 }),
	dateTo: varchar("date_to", { length: 20 }),
	hoursNumber: int("hours_number"),
	typeOfLd: varchar("type_of_ld", { length: 50 }),
	conductedBy: varchar("conducted_by", { length: 255 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
},
(table) => [
	index("idx_app_train_id").on(table.applicantId),
	primaryKey({ columns: [table.id], name: "applicant_training_id"}),
]);

export const applicantEligibility = mysqlTable("applicant_eligibility", {
	id: int("id").autoincrement().notNull(),
	applicantId: int("applicant_id").notNull().references(() => recruitmentApplicants.id, { onDelete: "cascade" } ),
	eligibilityName: varchar("eligibility_name", { length: 255 }).notNull(),
	rating: decimal("rating", { precision: 5, scale: 2 }),
	examDate: varchar("exam_date", { length: 20 }),
	examPlace: varchar("exam_place", { length: 255 }),
	licenseNumber: varchar("license_number", { length: 50 }),
	validityDate: varchar("validity_date", { length: 20 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
},
(table) => [
	index("idx_app_elig_id").on(table.applicantId),
	primaryKey({ columns: [table.id], name: "applicant_eligibility_id"}),
]);

export const recruitmentEmailTemplates = mysqlTable("recruitment_email_templates", {
	id: int("id").autoincrement().notNull(),
	stageName: varchar("stage_name", { length: 50 }).notNull(),
	subjectTemplate: varchar("subject_template", { length: 255 }).notNull(),
	bodyTemplate: text("body_template").notNull(),
	availableVariables: text("available_variables"),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "recruitment_email_templates_id"}),
	unique("stage_name").on(table.stageName),
]);

export const recruitmentSecurityLogs = mysqlTable("recruitment_security_logs", {
	id: int("id").autoincrement().notNull(),
	jobId: int("job_id"),
	firstName: varchar("first_name", { length: 100 }),
	lastName: varchar("last_name", { length: 100 }),
	email: varchar("email", { length: 255 }),
	violationType: varchar("violation_type", { length: 100 }), // e.g., 'Identity Fraud', 'Duplicate', 'Spam Bot'
	details: text("details"),
	ipAddress: varchar("ip_address", { length: 45 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
},
(table) => [
	index("idx_violation").on(table.violationType),
	primaryKey({ columns: [table.id], name: "recruitment_security_logs_id"}),
]);


