export interface HiredApplicant {
  id: number;
  firstName: string;
  lastName: string;
  middleName: string | null;
  suffix: string | null;
  email: string;
  phoneNumber: string | null;
  photoPath: string | null;
  photoUrl: string | null;
  birthDate: string | null;
  birthPlace: string | null;
  sex: 'Male' | 'Female' | null;
  civilStatus: 'Single' | 'Married' | 'Widowed' | 'Separated' | 'Annulled' | null;
  height: string | null;
  weight: string | null;
  bloodType: string | null;
  gsisNumber: string | null;
  pagibigNumber: string | null;
  philhealthNumber: string | null;
  umidNumber: string | null;
  philsysId: string | null;
  tinNumber: string | null;
  eligibility: string | null;
  eligibilityType: string | null;
  eligibilityDate: string | null;
  eligibilityRating: string | null;
  eligibilityPlace: string | null;
  licenseNo: string | null;
  address: string | null;
  zipCode: string | null;
  permanentAddress: string | null;
  permanentZipCode: string | null;
  resHouseBlockLot: string | null;
  resStreet: string | null;
  resSubdivision: string | null;
  resBarangay: string | null;
  resCity: string | null;
  resProvince: string | null;
  resRegion: string | null;
  permHouseBlockLot: string | null;
  permStreet: string | null;
  permSubdivision: string | null;
  permBarangay: string | null;
  permCity: string | null;
  permProvince: string | null;
  permRegion: string | null;
  isMeycauayanResident: boolean | null;
  educationalBackground: string | null;
  schoolName: string | null;
  course: string | null;
  yearGraduated: string | null;
  experience: string | null;
  skills: string | null;
  totalExperienceYears: string | number | null;
  emergencyContact?: string | null;
  emergencyContactNumber?: string | null;
  hiredDate: string | null;
  startDate: string | null;
  department?: string | null;
  jobTitle?: string | null;
  employmentType?: string | null;
  dutyType?: 'Standard' | 'Irregular' | null;
}
