export interface HiredApplicant {
  id: number;
  first_name: string;
  last_name: string;
  middle_name: string | null;
  suffix: string | null;
  email: string;
  phone_number: string | null;
  photo_path: string | null;
  photo_url: string | null;
  birth_date: string | null;
  birth_place: string | null;
  sex: 'Male' | 'Female' | null;
  civil_status: 'Single' | 'Married' | 'Widowed' | 'Separated' | 'Annulled' | null;
  height: string | null;
  weight: string | null;
  blood_type: string | null;
  gsis_no: string | null;
  pagibig_no: string | null;
  philhealth_no: string | null;
  umid_no: string | null;
  philsys_id: string | null;
  tin_no: string | null;
  eligibility: string | null;
  eligibility_type: string | null;
  eligibility_date: string | null;
  eligibility_rating: string | null;
  eligibility_place: string | null;
  license_no: string | null;
  address: string | null;
  zip_code: string | null;
  permanent_address: string | null;
  permanent_zip_code: string | null;
  is_meycauayan_resident: number | null;
  education: string | null;
  school_name: string | null;
  course: string | null;
  year_graduated: string | null;
  experience: string | null;
  skills: string | null;
  total_experience_years: string | number | null;
  hired_date: string | null;
  department?: string | null;
  job_title?: string | null;
}
